### ISSUE TITLE
Crash in kernel version DBSCAN workload

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba#22]
The kernel version of DBSCAN completes execution. However, at the end of the execution a crash occurs. See below.

*************
Exception ignored in: <function Program.__del__ at 0x7f429d153430>
Traceback (most recent call last):
  File "/localdisk/work/adarshyoga/software/miniconda3/envs/build-env/lib/python3.8/site-packages/dppl/ocldrv.py", line 237, in __del__
AttributeError: 'NoneType' object has no attribute 'destroy_dp_program'
Exception ignored in: <function Kernel.__del__ at 0x7f429d1535e0>
Traceback (most recent call last):
  File "/localdisk/work/adarshyoga/software/miniconda3/envs/build-env/lib/python3.8/site-packages/dppl/ocldrv.py", line 264, in __del__
AttributeError: 'NoneType' object has no attribute 'destroy_dp_kernel'
*************

**Comment by adarshyoga** [comment]
To reproduce the error run the DBSCAN workload in the Numba_Benchmarks repository ([link](https://github.intel.com/adarshyo/Numba_Benchmarks/blob/master/numba/dbscan/GPU/dbscan.py)).

Steps to execute:
1) Setup PyDPPL and Numba-PyDPPL

2) cd to the dbscan directory
    > cd <path_to_Numba_Benchmarks>/numba/dbscan/GPU/

3) To run the workload execute,
     > python dbscan_kernel.py
    This command executes the workload for all the inputs. If interested in executing the workload for a single input run
     > python dbscan_kernel.py --steps 1

**Comment by adarshyoga** [comment]
This may be an issue with an incompatible versions of dependencies in the environment.  This behavior is not seen in OneApi shipped dependencies. Closing issue.
