### ISSUE TITLE
Numba 0.54 test fails with patches

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba#220]
```python-traceback
$ ./runtests.py 
Traceback (most recent call last):
  File "/localdisk/work/spokhode/numba/numba/testing/__init__.py", line 29, in load_testsuite
    suite.addTests(loader.loadTestsFromName(f))
  File "/localdisk/work/spokhode/miniconda3/envs/numba-dppy-numba0.54-py38/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/localdisk/work/spokhode/numba/numba/tests/doc_examples/test_structref_usage.py", line 58, in <module>
    def MyStruct_get_name(self):
  File "/localdisk/work/spokhode/numba/numba/core/decorators.py", line 301, in njit
    return jit(*args, **kws)
  File "/localdisk/work/spokhode/numba/numba/core/decorators.py", line 180, in jit
    wrapper = _jit(sigs, locals=locals, target=target, cache=cache,
  File "/localdisk/work/spokhode/numba/numba/core/decorators.py", line 191, in _jit
    dispatcher = resolve_dispatcher_from_str(target)
  File "/localdisk/work/spokhode/numba/numba/core/target_extension.py", line 76, in resolve_dispatcher_from_str
    target_hw = resolve_target_str(target_str)
  File "/localdisk/work/spokhode/numba/numba/core/target_extension.py", line 71, in resolve_target_str
    return target_registry[target_str]
  File "/localdisk/work/spokhode/numba/numba/core/target_extension.py", line 20, in __getitem__
    raise ValueError(msg.format(item, known)) from None
ValueError: No target is registered against 'None', known targets:
generic    -> <class 'numba.core.target_extension.Generic'>
CPU        -> <class 'numba.core.target_extension.CPU'>
cpu        -> <class 'numba.core.target_extension.CPU'>
GPU        -> <class 'numba.core.target_extension.GPU'>
gpu        -> <class 'numba.core.target_extension.GPU'>
CUDA       -> <class 'numba.core.target_extension.CUDA'>
cuda       -> <class 'numba.core.target_extension.CUDA'>
ROCm       -> <class 'numba.core.target_extension.ROCm'>
npyufunc   -> <class 'numba.core.target_extension.NPyUfunc'>
```

**Comment by PokhodenkoSA** [comment]
Fixed by 89b45686dce23f43f6bad6c0fbd2a796b301e83a
